### ISSUE TITLE
Implement newer syntax changes

### ISSUE THREAD

**Issue by moqmar** [vitalibo/bitbake-intellij-plugin#5] opened 2022-07-12 09:48 UTC
For example the new override syntax from https://docs.yoctoproject.org/migration-guides/migration-3.4.html, or stuff like `SRC_URI[name.md5sum]`, currently breaks the highlighter.

**Comment by ShaneMurphy2** [comment] 2022-09-26 21:04
Out of curiosity, anyone know _why_ they changed from _prepend to :prepend and the like?

**Comment by moqmar** [comment] 2022-10-03 07:51
That's explained in the link above, seems like it makes it easier to parse internally and also easier to read:

> For reference, this conversion is important as it allows BitBake to more reliably determine what is an override and what is not, as underscores are also used in variable names without intending to be overrides. This should allow us to proceed with other syntax improvements and simplifications for usability. It also means BitBake no longer has to guess and maintain large lookup lists just in case e.g. functionname in my_functionname is an override, and thus should improve efficiency.

**Comment by jaskij** [comment] 2022-10-12 17:41
@ShaneMurphy2  on the easier to read part: try porting files from old syntax to new syntax manually. You *will* make mistakes. Showing that yes, it's hard to know what is and what isn't an override.

**Comment by DavidAntliff** [comment] 2023-06-07 05:10
This plugin is _almost_ working with the new syntax, but it's still not quite right.

I see there's a pending PR to add support: https://github.com/vitalibo/bitbake-intellij-plugin/pull/8

@vitalibo what would it take to get this PR into the published plugin? Maybe we could get a build to test, please?

**Comment by moqmar** [comment] 2023-06-07 12:45
Here's a build of the PR branch of #8, feel free to test with it:

~~[BitBake-1.3.zip](https://github.com/vitalibo/bitbake-intellij-plugin/files/11677150/BitBake-1.3.zip)~~
[BitBake-1.3.zip](https://github.com/vitalibo/bitbake-intellij-plugin/files/11684954/BitBake-1.3.zip)

I'll merge it in a couple of days, but would be glad to get some feedback from people who're already using the newer syntax.

**Comment by DavidAntliff** [comment] 2023-06-07 21:22
> Here's a build of the PR branch of #8, feel free to test with it:
> 
> [BitBake-1.3.zip](https://github.com/vitalibo/bitbake-intellij-plugin/files/11677150/BitBake-1.3.zip)
> 
> I'll merge it in a couple of days, but would be glad to get some feedback from people who're already using the newer syntax.

Thanks - I gave it a try (installed, restarted PyCharm Pro) but it doesn't seem to be catching all cases:

![image](https://github.com/vitalibo/bitbake-intellij-plugin/assets/11261038/9cfde2e4-b344-46eb-833e-a7e7ed2f29c5)

![image](https://github.com/vitalibo/bitbake-intellij-plugin/assets/11261038/3a1fce8a-f80b-4781-b13e-1688edeec2e7)

![image](https://github.com/vitalibo/bitbake-intellij-plugin/assets/11261038/f3ee1ed1-01c5-4814-ab9f-4510233f1a92)

![image](https://github.com/vitalibo/bitbake-intellij-plugin/assets/11261038/0296247f-9021-4e87-9598-5d56ffbf2509)

It's difficult to tell but I don't think it's picking up the new syntax at all?

EDIT: Just to be sure, I completely uninstalled and then reinstalled from the .zip but I still see the same as the screenshots above.

**Comment by moqmar** [comment] 2023-06-08 06:57
Whoops, sorry, I've uploaded the wrong file - link should now be fixed.

**Comment by DavidAntliff** [comment] 2023-06-08 22:38
That works much better - thank you.

There are still some issues with some of the `.bb` and `.bbclass` files I am working with:

In a `.bbclass` file: `meta-swupdate/classes-recipe/swupdate.bbclass`:
![image](https://github.com/vitalibo/bitbake-intellij-plugin/assets/11261038/857eb620-756d-4025-b193-021fbf8ffd8e)

Another `.bbclass`: `meta-xilinx-tools/classes/fpgamanager_dtg.bbclass`:
![image](https://github.com/vitalibo/bitbake-intellij-plugin/assets/11261038/ce44aba5-5176-4b44-b1cd-1f724514bff5)
(followed by "Unresolved reference 'd'", which might be a global?), then for the underlined `python devicetree_do_compile:append()` there's "BitBakeTokenType.OPERATOR expected, got 'devicetree_do_compil...'".

![image](https://github.com/vitalibo/bitbake-intellij-plugin/assets/11261038/647371cc-f49e-4d8f-aeae-85b067e7f162)

Same file - no tooltip for the underlined "." in `fw_env.config`:
![image](https://github.com/vitalibo/bitbake-intellij-plugin/assets/11261038/2ab653cc-0ef6-42b3-9a60-e35565e758d3)

There are others too, but they may be caused by those. Happy to help keep testing new builds.

**Comment by ShaneMurphy2** [comment] 2023-06-13 22:56
I'm also trying out the new build, seeing similar errors to @DavidAntliff.

**Comment by DavidAntliff** [comment] 2023-08-28 23:33
Just leaving a comment to say that I'm still happy to test any updates to this plugin. I have a whole bitbake project with red squiggles I can set a new build of this plugin against, and report back any remaining cases :)

**Comment by fbezdeka** [comment] 2024-07-30 22:44
So... Here we go. I updated #8 with the result of my one day holiday hacking. Feedback welcome! Testing will start here as well.

**Comment by DavidAntliff** [comment] 2024-08-01 05:45
I'm trying the version from [this build](https://github.com/fbezdeka/bitbake-intellij-plugin/actions/runs/10178590486/artifacts/1759583652) and it's working better overall, but I do see some irregularities still. Here's a few:

![image](https://github.com/user-attachments/assets/61782151-1723-491b-8408-9591bc118915)

![image](https://github.com/user-attachments/assets/4e3a5dd3-5c79-411d-b9a4-59dceee75ec5)

![image](https://github.com/user-attachments/assets/2784a4f3-df87-4d8a-8dbc-5f8e30fea174)

![image](https://github.com/user-attachments/assets/d833e269-5e1e-4b7a-bfe4-249f2667e933)

![image](https://github.com/user-attachments/assets/9634e093-3d85-4e3c-a8e7-7f31c27e80ef)

![image](https://github.com/user-attachments/assets/5053b179-a358-4135-871f-f1fb368a3fc3)

**Comment by fbezdeka** [comment] 2024-08-01 08:31
Thanks for providing the feedback!

I think these are different issues and should not be mixed with the "newer syntax" issue here. Could you open two different issues (as you are the real reporter I think this makes sense) please?

- One for a broken comment parsing (## at the beginning of a line - with no further content - breaks the parser).
- One for export statements require a value assignment (`export VAR` breaks the parser, while `export VAR="value"` is OK)

~~I'm not able to reproduce the "illegal target for variable annotation" yet.~~

I can handle the "illegal target for variable annotation" in this MR. It's kind of related. Bug in the python language injection.

**Comment by fbezdeka** [comment] 2024-08-01 17:27
I updated #8 again. Latest build artifacts can be fetched from here: https://github.com/fbezdeka/bitbake-intellij-plugin/actions/runs/10202860522/artifacts/1765892776

I think I covered all reported problems. Feedback welcome.

**Comment by DavidAntliff** [comment] 2024-08-01 21:35
@fbezdeka thanks, I've just installed [this](https://github.com/fbezdeka/bitbake-intellij-plugin/actions/runs/10202860522/artifacts/1765892776) and it seems to have cleared up the issues above - fantastic.

I am now going through a big set of .bb files looking for any outstanding or new cases.

In most cases I can provide the .bb file if that helps - just ask...

... looks like there's only a few left now:

![image](https://github.com/user-attachments/assets/c1104b27-2276-4d71-bc71-350e76f6506a)

That "= after export" one you mentioned before, I suspect:

![image](https://github.com/user-attachments/assets/e2509ef2-de17-412e-a365-ba1939a739ae)

(Also happens with the `:=` in `export FOO := "..."`).

I guess this next one is just because there's no active Python environment when editing .bb files:

![image](https://github.com/user-attachments/assets/200c37d1-0ad3-49f8-8538-2045ff6609ec)

This is from a weird Xilinx file. I'm sure what they are doing with that import before function docstring, but the syntax highlighting seems to turn off, and there's a strange error right at the end:

![image](https://github.com/user-attachments/assets/6d940c1a-2944-483e-83a8-88d277f53039)

Other than those it's looking really good - almost there!

Thank you.

**Comment by DavidAntliff** [comment] 2024-08-01 21:37
> I think these are different issues and should not be mixed with the "newer syntax" issue here. Could you open two different issues (as you are the real reporter I think this makes sense) please?
> 
>     * One for a broken comment parsing (## at the beginning of a line - with no further content - breaks the parser).
> 
>     * One for export statements require a value assignment (`export VAR` breaks the parser, while `export VAR="value"` is OK)

I think the first is now fixed. Would you still like me to open a new issue for the second one?

There's also `EXPORT_FUNCTIONS` as per screenshot above.

**Comment by fbezdeka** [comment] 2024-08-02 11:02
Everything related to `export` and `EXPORT_FUNCTION` should be fixed now. The latest build result is linked in #8.

The python "no module named ..." might be fixed by proper configuration of the python interpreter. I think we can't handle that on plugin level.

The last remaining is the broken highlighting for this python function. Might it be that this function is at the end of the file? ~~Could you provide the file?~~ No longer necessary. I was able to reproduce. Already fixed in #8

**Comment by DavidAntliff** [comment] 2024-08-02 22:16
@fbezdeka looks really good! This is such a great improvement. Thank you.

There are two issues remaining that I can see. I'll mention them here but if you'd prefer a new issue then let me know and I'll create one (or two).

This is from a `.inc` file, commonly included by a `.bb`:

![image](https://github.com/user-attachments/assets/a4867132-47b2-448e-adc0-893372805cfb)

Multiple `EXPORT_FUNCTIONS` on the same line:

![image](https://github.com/user-attachments/assets/681a9aa2-3c1d-43d5-a2b9-0271be662401)

I took a look into the python interpreter. I'm using IDEA so this is set under Project Structure > Project Settings > Project, where I have the Project SDK set as Python 3.10:

![image](https://github.com/user-attachments/assets/0e94b7f0-e21c-4e44-a5f2-9a946526b546)

I see the breadcrumbs at the bottom of the IDE showing it as "... > externalxsctsrc.bbclass > \<Injected Python file\>".

But then I found [this](https://stackoverflow.com/a/61983673), so removing the Project Settings > Modules entry and then creating a new Modules entry with an existing Interpreter fixed this issue. So I think we're good on that one now.

![image](https://github.com/user-attachments/assets/9f5d0920-a50b-4a97-9c01-253f6238cce8)

**Comment by fbezdeka** [comment] 2024-08-05 10:33
Hopefully the last two remaining issues (flags parsing + multiple functions in EXPORT_FUNCTIONS) are fixed now. MR has been updated.

**Comment by DavidAntliff** [comment] 2024-08-05 23:30
Thanks @fbezdeka, it looks really good to me. I found a couple of minor issues but I can create new issues for them at some stage, they are minor and don't relate to any of the issues reported above.

Thank you again for your efforts with this, it will make it a much better experience when working with .bb files.

Let's get this reviewed and merged. Pinging @vitalibo...

**Comment by fbezdeka** [comment] 2024-08-09 10:20
#8 was merged. Closing as everything else should be handled in separate issues.

**Closed as completed by fbezdeka** 2024-08-09 10:20 UTC
